### ISSUE TITLE
Epic

### ISSUE THREAD

**Issue by PhoenixNazarov** [PhoenixNazarov/prompt-admin#5]
Prompt-admin features
- [x] #1
- [x] #6
- [x] #8
- [x] Show project tables
- [x] #10
- [x] #9
- [x] #7
- [x] #11
- [x] #12
- [x] Ai context
- [x] #13
- [x] #15
- [x] Ssr for save path. SsrStore 
- [x] #16
- [x] Jinja errors in Codemirror
- [x] Output format 
- [x] Window tabs
- [x] Jinja parsing in codemirror
- [x] Vuetify migration, add loadings
- [x] Output format calculator
- [x] Config store. Local store https://runthatline.com/how-to-use-local-storage-pinia/

Output format 
- [x] Use for actual prompt with preview
- [x] Calculator
- [x] Create standart
- [x] Need add OR

Library
- [x] #14
- [x] Contexts
- [x] Messages
- [x] Output
- [ ] Documentation
- [ ] Settings
- [x] #17
- [ ] Set settings in prompt admin
- [x] Push to pip

Bugs:
- [ ] Save when prompt changed
